[package]
name = "shards-tech/enums"
description = "Define a custom built Enum. Taken from `sleitnick` for modifications. https://github.com/shards-tech/device.git"
authors = ["Bloomy <dequeyuri@gmail.com>"]

version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["init.lua", "wally.toml"]
